### ISSUE TITLE
Get  TypeError: Cannot read property 'highWaterMark' of undefined

### ISSUE THREAD

**Issue by LiaqatSaeed** [jaystack/odata-v4-server-mssql-example#4]
I downloaded **odata-v4-server-mssql-example**. I have created database and i have changed Config in the connect.ts   But i run  ***NPM TEST***  its throwing me this error. Need quick help on this

**Comment by atul221282** [comment]
I am getting the same error and it looks like this project is dead

**Comment by Steentje86** [comment]
I am getting the same error.

**Comment by ederj12** [comment]
I am getting the same error.

mocha test/*.spec.js --reporter mochawesome --reporter-options reportDir=report,reportName=odata-v4-server,reportTitle="OData V4 Server"



  OData V4 example server
    Products
      1) "before each" hook for "should get all products (GET /Products)"


  0 passing (69ms)
  1 failing

  1) OData V4 example server
       "before each" hook for "should get all products (GET /Products)":
     TypeError: Cannot read property 'highWaterMark' of undefined
      at ODataServer.get (_stream_duplex.js:75:32)
      at propNames.forEach (node_modules\odata-v4-server\build\lib\metadata.js:295:49)
      at Array.forEach (<anonymous>)
      at Object.createMetadataJSON (node_modules\odata-v4-server\build\lib\metadata.js:294:15)
      at Function.$metadata (node_modules\odata-v4-server\build\lib\server.js:187:137)
      at new ODataProcessor (node_modules\odata-v4-server\build\lib\processor.js:416:81)
      at Function.createProcessor (node_modules\odata-v4-server\build\lib\server.js:176:16)
      at Function.execute (node_modules\odata-v4-server\build\lib\server.js:145:30)
      at Context.beforeEach (test\mssql.spec.js:55:32)
